### ISSUE TITLE
Create basic project directories layout, third party dependencies and update README

### ISSUE THREAD

**Issue by dystonie** [nexocrew/3nigm4#1]
To be done @dystonie:

- [create basic files and directories]
- [add required basic dependencies (crypto libs and other)]
- [update README.md]

**Comment by FedericoMaggi** [comment]
How do we want to organise the repo?

I was thinking about:

    repo
    |
    |- 3nigm4-server
    |   |- bin
    |   |- pkg
    |   `- src
    |
    |- 3nigm4-client
    |  |- bin
    |  |- pkg
    |  `- src 
    |
    |- 3nigm4-daemon
    |  |- bin
    |  |- pkg
    |  `- src 
    |
    |- build-script
    |
    |- docs

**Comment by dystonie** [comment]
To be as golang compliant as possible I suggest having, under src path in GOPATH:

repo (3nigm4)
|
|- server
|   |- api
|   |- db
|   |- core
| 
|- client
|   |- cli
|   |- deamon 
|
|- libs
|   |- crypto
|   |- version
|   |- args
|
|- build-scripts
|   |- docker
|
|- docs

Does it make sense to you? Having this layout let us include a Makefile to build, test and benchmark all code from a single point.

**Comment by FedericoMaggi** [comment]
Yeah, I thought the repo to be a collection of more than one Go project (thus more than one GOPATH). 
Anyway this layout is more convenient :)

**Comment by dystonie** [comment]
I've noticed that with this dir layout it's impossible to inlcude libs using "import github.com/nexocrew/3nigm4". I'm moving all project dirs removing references to src, pkg and bin dir.
