### ISSUE TITLE
use standard convention to comment imports

### ISSUE THREAD

**Issue by fredmaggiowski** [nexocrew/3nigm4#35]
We should keep a standard convention to comment our imports.
If everyone agrees we should all migrate our comments to a unified standard.

I suggest the usage of:
`// Go standard libraries`
`// 3n4 libraries`
`// Third party libraries`

**Comment by dystonie** [comment]
My suggestion:

```
// Golang std libs
import ()

// Internal dependencies
import ()

// Third party libs
import ()
```

**Comment by fredmaggiowski** [comment]
Why do you refer to internals as _dependencies_ and others as _libs_?

**Comment by dystonie** [comment]
Lets refactor:

```
// Golang std pkgs
import ()

// Internal pkgs
import ()

// Third party pkgs
import ()
```

**Comment by fredmaggiowski** [comment]
OK, this is fine to me :)
